name       : pipenv
version    : 2021.5.29
release    : 6
source     :
    - https://github.com/pypa/pipenv/archive/refs/tags/v2021.5.29.tar.gz : 7db6265da20f4fba3be6caa41d8692ce9342ce84cd68da281134a03cff029425
license    : MIT
component  : programming.python
summary    : Python Development Workflow for Humans
description: |
    Pipenv is a tool that aims to bring the best of all packaging worlds (bundler, composer, npm, cargo, yarn, etc.) to the Python world
builddeps  :
    - python-arpeggio
    - python-attrs
    - python-invoke
    - python-parver
    - python-setuptools
rundeps    :
    - pip
    - python-certifi
    - virtualenv
    - virtualenv-clone
build      : |
    %python3_setup
install    : |
    %python3_install
