name       : pipenv
version    : 2022.5.2
release    : 10
source     :
    - https://github.com/pypa/pipenv/archive/refs/tags/v2022.5.2.tar.gz : 1f544bf6f384dad317b5eee306356ca563ac9d8246f555af7a8c611c028a12e2
homepage   : https://pipenv.pypa.io/
license    : MIT
component  : programming.python
summary    : Python Development Workflow for Humans
description: |
    Pipenv is a tool that aims to bring the best of all packaging worlds (bundler, composer, npm, cargo, yarn, etc.) to the Python world.
builddeps  :
    - python-invoke
    - python-parver
rundeps    :
    - python-certifi
    - virtualenv
    - virtualenv-clone
build      : |
    %python3_setup
install    : |
    %python3_install
