name       : pipenv
version    : 2021.11.15
release    : 7
source     :
    - https://github.com/pypa/pipenv/archive/refs/tags/v2021.11.15.tar.gz : 97dbfa07e115996e43bb153c050b0d28b47888d36cec7eebd061a1b1b125d167
homepage   : https://pipenv.pypa.io/
license    : MIT
component  : programming.python
summary    : Python Development Workflow for Humans
description: |
    Pipenv is a tool that aims to bring the best of all packaging worlds (bundler, composer, npm, cargo, yarn, etc.) to the Python world.
builddeps  :
    - python-invoke
    - python-parver
rundeps    :
    - python-certifi
    - virtualenv
    - virtualenv-clone
build      : |
    %python3_setup
install    : |
    %python3_install
