name       : pipenv
version    : 2022.9.8
release    : 13
source     :
    - https://github.com/pypa/pipenv/archive/refs/tags/v2022.9.8.tar.gz : 3c91c0d7758b1f7366c635ecbd3b6b502d50c9e51b795de066d7fca155c7fa2e
homepage   : https://pipenv.pypa.io/
license    : MIT
component  : programming.python
summary    : Python Development Workflow for Humans
description: |
    Pipenv is a tool that aims to bring the best of all packaging worlds (bundler, composer, npm, cargo, yarn, etc.) to the Python world.
rundeps    :
    - python-certifi
    - virtualenv
    - virtualenv-clone
build      : |
    %python3_setup
install    : |
    %python3_install
