name       : pipenv
version    : 2018.7.1
release    : 1
source     :
    - https://github.com/pypa/pipenv/archive/v2018.7.1.tar.gz : e7428c4a3ac93b8ad0a7819e043191865fc75b93a4a26a7288bf2a12883bca7a
license    : MIT
component  : programming.python
summary    : Python Development Workflow for Humans
description: |
    Pipenv is a tool that aims to bring the best of all packaging worlds (bundler, composer, npm, cargo, yarn, etc.) to the Python world
builddeps  :
    - python-arpeggio
    - python-attrs
    - python-invoke
    - python-parver
    - python-setuptools
rundeps    :
    - pip
    - python-certifi
    - virtualenv
    - virtualenv-clone
build      : |
    %python3_setup
install    : |
    %python3_install
