name       : pipenv
version    : 2022.1.8
release    : 8
source     :
    - https://github.com/pypa/pipenv/archive/refs/tags/v2022.1.8.tar.gz : 6bf64140bf240689a84447e376030da766afee76ecd3a082fbf2dbdb26a170d7
homepage   : https://pipenv.pypa.io/
license    : MIT
component  : programming.python
summary    : Python Development Workflow for Humans
description: |
    Pipenv is a tool that aims to bring the best of all packaging worlds (bundler, composer, npm, cargo, yarn, etc.) to the Python world.
builddeps  :
    - python-invoke
    - python-parver
rundeps    :
    - python-certifi
    - virtualenv
    - virtualenv-clone
build      : |
    %python3_setup
install    : |
    %python3_install
